#!/usr/bin/env python3
"""Rebuild the historical data cache the analysis layer reads.

The analysis scripts (analyze_recency, analyze_injury, replay_backtest,
analyze_durability) read a local cache of public historical data. The
committed payloads in out/data/ are the results of record; this script
exists so anyone can rebuild that cache from the original sources and
reproduce them byte-for-byte (tests/test_analysis.py reruns every
analysis end-to-end whenever the cache is present, and skips those
reruns - loudly - when it is not).

Cache location: the HISTORY environment variable if set, else the same
default path the analysis scripts use (src/analyze_recency.py HISTORY).

Contents (all public):
  ffc_ppr_YYYY.json   FantasyFootballCalculator PPR ADP, 12-team boards,
                      2013-2025 (early-September snapshots)
  spw_YYYY.csv        nflverse stats_player_week, 2012-2025 (CC-BY-4.0)
  inj_YYYY.csv        nflverse injury reports, 2012-2025 (CC-BY-4.0);
                      the release stores some years gzipped and some
                      plain, so both are tried
  roster_YYYY.csv     nflverse rosters, 2013-2025 (CC-BY-4.0) - birth
                      dates for the age control in the durability study
  pbp_2025.parquet            nflverse play-by-play (build_cvs_inputs, C5)
  participation_2025.parquet  nflverse pbp participation - the route proxy
  ftn_2025.parquet            FTN charting via nflverse - first-read share
  advrush_2025.parquet        PFR advanced rushing, weekly - contact metrics
  games.csv                   nflverse schedules/results (WS2 claim 8)

THE FIVE SINGLE-SEASON FILES WERE ADDED 2026-08-26 AND THIS IS WHY.
The self-audit found that this script downloaded four families while the
builders read nine. The five it did not know about had no URL recorded
anywhere in the repository - not here, not in any doc, not in artifact
provenance - so src/build_bullish_inputs.py (the C5 BULLISH inputs) and
one claim in src/build_ws2_audit.py could not be regenerated by anyone,
and the reproducibility guarantee this file was committed to provide had
silently lapsed as later work added dependencies it never learned about.
Each URL below was verified by downloading it and byte-comparing against
the cache that produced the committed artifacts. tests/test_pages_data.py
now asserts that every HISTORY filename any src/ module reads is a family
this fetcher knows, so the gap cannot silently reopen.

games.csv is the one source that is NOT a versioned release: habitatring
serves a live file that nflverse regenerates continuously, so a fresh
pull will differ from the cached copy by a few bytes as later games are
scored. That is expected; it is not a reproducibility failure, but any
recomputation of a games.csv-derived number should state its pull date.

Idempotent by default: files already present (and non-trivial in size) are kept.
The daily producer passes --refresh-live so the one unversioned input, games.csv,
is fetched again while the versioned 156 MB cache remains reusable.

Run: python3 src/fetch_history.py                    # complete cache only
     python3 src/fetch_history.py --refresh-live     # also refresh games.csv
     HISTORY=/somewhere python3 src/fetch_history.py
"""
import argparse
import gzip
import os
import sys
import urllib.request
from contextlib import closing

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from analyze_recency import HISTORY


def fetch(url, dest, gz=False, refresh=False, required_prefix=None):
    if not refresh and os.path.exists(dest) and os.path.getsize(dest) > 1000:
        return "have"
    tmp = dest + ".tmp"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "ytfl-hub"})
        with closing(urllib.request.urlopen(req, timeout=180)) as response:
            raw = response.read()
        if gz:
            raw = gzip.decompress(raw)
        if len(raw) <= 1000:
            raise ValueError(f"response too small ({len(raw)} bytes)")
        if required_prefix and not raw.startswith(required_prefix):
            raise ValueError("response does not have the expected file header")
        with open(tmp, "wb") as fh:
            fh.write(raw)
        os.replace(tmp, dest)
        return "ok"
    except Exception as e:
        if os.path.exists(tmp):
            os.unlink(tmp)
        return f"FAIL {e}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--refresh-live", action="store_true",
        help="re-fetch unversioned games.csv while retaining versioned cache files")
    args = parser.parse_args()
    os.makedirs(HISTORY, exist_ok=True)
    results = []
    for y in range(2013, 2026):
        results.append((f"ffc_ppr_{y}.json", fetch(
            f"https://fantasyfootballcalculator.com/api/v1/adp/ppr?teams=12&year={y}",
            os.path.join(HISTORY, f"ffc_ppr_{y}.json"))))
    for y in range(2012, 2026):
        results.append((f"spw_{y}.csv", fetch(
            "https://github.com/nflverse/nflverse-data/releases/download/"
            f"stats_player/stats_player_week_{y}.csv.gz",
            os.path.join(HISTORY, f"spw_{y}.csv"), gz=True)))
    for y in range(2012, 2026):
        dest = os.path.join(HISTORY, f"inj_{y}.csv")
        base_url = ("https://github.com/nflverse/nflverse-data/releases/"
                    f"download/injuries/injuries_{y}.csv")
        r = fetch(base_url + ".gz", dest, gz=True)
        if r.startswith("FAIL"):
            r = fetch(base_url, dest)
        results.append((f"inj_{y}.csv", r))
    for y in range(2013, 2026):
        results.append((f"roster_{y}.csv", fetch(
            "https://github.com/nflverse/nflverse-data/releases/download/"
            f"rosters/roster_{y}.csv",
            os.path.join(HISTORY, f"roster_{y}.csv"))))

    # single-season inputs for the C5/C6 builders. Verified byte-identical
    # to the cache that produced the committed artifacts on 2026-08-26.
    NV = "https://github.com/nflverse/nflverse-data/releases/download"
    for local, url in (
            ("pbp_2025.parquet", f"{NV}/pbp/play_by_play_2025.parquet"),
            ("participation_2025.parquet",
             f"{NV}/pbp_participation/pbp_participation_2025.parquet"),
            ("ftn_2025.parquet", f"{NV}/ftn_charting/ftn_charting_2025.parquet"),
            ("advrush_2025.parquet",
             f"{NV}/pfr_advstats/advstats_week_rush_2025.parquet")):
        results.append((local, fetch(url, os.path.join(HISTORY, local))))
    # Live file, not a versioned release. The producer opts into refreshing it;
    # reproducibility runs retain the cache they were pointed at.
    results.append(("games.csv", fetch(
        "http://www.habitatring.com/games.csv",
        os.path.join(HISTORY, "games.csv"), refresh=args.refresh_live,
        required_prefix=b"game_id,season,game_type,week,")))

    bad = [(f, r) for f, r in results if r.startswith("FAIL")]
    for f, r in results:
        print(f"{r:>5}  {f}" if not r.startswith("FAIL") else f"{f}: {r}")
    print(f"\ncache at {HISTORY}: {len(results) - len(bad)}/{len(results)} present"
          + ("" if not bad else " - FAILURES ABOVE"))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
